### ISSUE TITLE
Posibility for optimisation in ParameterizedTypeImpl.java 

### ISSUE THREAD

**Issue by alexVengrovsk** [codenvy/che-core#206]
After looking to ```ParameterizedTypeImpl.java```, it is not very clear, why there are so many private constructors? It is posible to use only two constructors
```
private ParameterizedTypeImpl(Class<?> rawType, Type typeArgument) {
        this.rawType = rawType;
        this.typeArguments = new Type[]{typeArgument};
    }

private ParameterizedTypeImpl(Class<?> rawType, Type[] typeArguments) {
        this.rawType = rawType;
        this.typeArguments = new Type[typeArguments.length];
        System.arraycopy(typeArguments, 0, this.typeArguments, 0, this.typeArguments.length);
    }
```
as any of stacic generation methods (```newParameterizedType(Class<?> rawType, Type... typeArguments) and newParameterizedType(Class<?> rawType, Type typeArgument)```) doesn't provide information for ```ownerType``` variable instantiation. According to current version of the class, this variable is allways ```null```. But it will be ```null``` by default.

All these three-parameter constructors is useful only, when one more method is added.
For example:
```
public static ParameterizedType newParameterizedType(Type ownerType, 
   Class<?> rawType, Type typeArgument) {
   return new ParameterizedTypeImpl(ownerType, rawType, typeArgument);
}
```

**Comment by skabashnyuk** [comment]
Are you ready to provide PR?

**Comment by alexVengrovsk** [comment]
Yes. I can do it today

**Comment by alexVengrovsk** [comment]
I added a PR. [#208](https://github.com/codenvy/che-core/pull/208)
