### ISSUE TITLE
Probable problems in CronExpression.java

### ISSUE THREAD

**Issue by alexVengrovsk** [codenvy/che-core#212]
1) Here is a method, that looks very strange for me (even if it wasn't used so far):
```
/**
     * Indicates whether the specified cron expression can be parsed into a
     * valid cron expression
     *
     * @param cronExpression
     *         the expression to evaluate
     * @return a boolean indicating whether the given expression is a valid cron
     * expression
     */
    public static boolean isValidExpression(String cronExpression) {
        new CronExpression(cronExpression);
        return true;
    }
```
It seems to be a validator for ```String parameter```. It returns boolean. But, here is a thing - this method returns or ```true``` or a ```RuntimeException``` (```IllegalArgumentException```) and never returns ```false```.

Not a very good behavior for validation. Especially, when no such information about this way of behavior in the method's contract (I mean - Javadoc).

And one more serious issue - productivity overhead, caused by creation of the new instance of ```IllegalArgumentException``` class.

2) I also think about deleting the ```expressionParsed``` variable. It doesn't look like a very useful one.

**Comment by alexVengrovsk** [comment]
Я не готов предоставить решение этой проблемы прямо сейчас, но я буду думать об этом (если никто не сделает это до меня).

**Comment by skabashnyuk** [comment]
Something like that?
```java
    public static boolean isValidExpression(String cronExpression) {
        
        try {
            new CronExpression(cronExpression);
        } catch (ParseException pe) {
            return false;
        }
        
        return true;
    }
```

**Comment by garagatyi** [comment]
@skabashnyuk  don't forget illegal argument exception
Looks like we don't use that method in our code at all and it was copied from origin code. So @alexVengrovsk I don't think we should care about efficiency of parsing with exception generation in that case.
http://svn.terracotta.org/svn/quartz/tags/quartz-1.8.6/quartz/src/main/java/org/quartz/CronExpression.java

**Comment by alexVengrovsk** [comment]
Yes. I mentioned too, that this method was never used. Maybe, it should be deleted, because in future somebody, possibly, will use it.

**Comment by skabashnyuk** [comment]
synced with c quartz 2.2.1 b7de5a75d7e860eab93bdd0090b044fd8c386ad4
